server:
  port: 8021

#  项目名称
spring:
  application:
    name: rabiit_provider

#    rabbitmq服务器配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

    # 在springboot2.3以后的版本中，下面这个配置属于删除状态，推荐使用后一种配置方式
#    publisher-confirms: true
    publisher-confirm-type: correlated
    # 下面这个配置，表示接收mq返回的确认消息
    publisher-returns: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#本地启动sentinel-dashboard.jar包可以正常限流   远程docker中不行
    sentinel:
      transport:
        dashboard: localhost:8858 #配置Sentinel dashboard地址
        port: 8719
        clientIp: localhost
      eager: true

